const USER_LOGGED_IN = 'USER_LOGGED_IN';
const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
const ACTIVE_GUIDELINE = 'ACTIVE_GUIDELINE';
const DISABLE_GUIDELINE = 'DISABLE_GUIDELINE';

export { ACTIVE_GUIDELINE, DISABLE_GUIDELINE, USER_LOGGED_IN, USER_LOGGED_OUT }
